# Executive summary {-}

**This report analyzes the effect of the City of Vancouver’s short-term rental (STR) regulations, with specific reference to their initial 2018 implementation and to the 2020 Covid-19 pandemic. It assesses the impact of the City’s STR regulations on the size and character of the STR market, and compares Vancouver’s performance with peer cities and with the rest of Metro Vancouver. And it provides an analysis of STR units that have returned to the longer-term rental market during the pandemic, describing their spatial distribution, asking rents, the extent to which they are commercial operations, and whether they are likely to return to the STR market when conditions improve.**

\noindent\rule{\textwidth}{1pt}

**SHORT-TERM RENTALS IN VANCOUVER: REGULATORY IMPACTS**

- The City of Vancouver’s STR licensing system has significantly and durably reduced the size of Vancouver’s STR market and the domination of the market by dedicated commercial operators. Vancouver now fares substantially better on these metrics than either its peer cities Montreal and Toronto or the rest of the Metro Vancouver region.
- The 2018 implementation of the City’s regulations created a one-time negative shock in the number of listings displayed on STR platforms in Vancouver, which dropped by 2,540, or 30.8% of the total displayed listings. This decline was disproportionately concentrated among listings which were present on STR platforms but not actively being rented; active listings dropped by 810, or 17.8%.
- Over the longer-term, we estimate that the regulations have reduced active STR listings by 1,510, or 35.8% of the total number of listings in the second half of 2019. The plausible range is 600to 1,670, and comparisons with other jurisdictions uniformly suggest that the real impact is at the higher end of this range.
- We estimate that the City’s regulations have returned 810 housing units to the long-term market, compared to the counter-factual scenario where the regulations were not in place. This is 38.9% of the average number of dedicated entire-home STRs taking housing off the Vancouver market in the second half of 2019. The plausible range for housing units returned to the market by the City’s regulations is quite large—from 160 to 990—but again, comparison with other jurisdictions suggests that the real impact is at the higher end of this range.
- Before the onset of the Covid-19 pandemic there were still upward of 2,500 housing units operating as dedicated STRs in Vancouver.

**COVID-19: STRS RETURNING TO THE LONG-TERM MARKET**

- Due to the combination of the City of Vancouver's ongoing STR regulations and the collapse in tourism demand during the COVID-19 pandemic, the number of STRs operating in a fashion consistent with being dedicated, full-time operations in Vancouver is the lowest it has been since at least 2016. Because of the collapse of STR demand during the COVID-19 pandemic, the number of housing units being operated as dedicated STRs in Vancouver dropped from 2,680 in January 2020 to just 940 in August 2020. 
- Using image recognition techniques, we identified 1,339 unique Airbnb listings which were posted as long-term rentals (LTRs) on Craigslist or Kijiji between March and September 2020. 
- These former STRs have asking rents on average 25.6% higher than other LTR listings, but are correlated with a 13.5% decrease in overall asking rents in Vancouver.
- The evidence suggests that the overwhelming majority of STR listings transferred to LTR platforms are commercial operations.
- We estimate that 30.6% have fully transitioned back to the long-term market, 35.3% have been temporarily blocked on Airbnb and may return to being STRs in the future, and 34.1% failed to be rented on LTR platforms and instead remain active on Airbnb.

\newpage