# Glossary {-}

Active daily listings: listings which were displayed on the Airbnb.ca or VRBO.ca website on a given day, and were either reserved or available for a reservation. It is the clearest means of determining the overall size of the short-term rental market in a location, particularly with respect to change over time.

FREH (frequently rented entire-home listings): Entire-home listings which were available on Airbnb or VRBO a majority of the year (at least 183 nights) and were booked a minimum of 90 nights. Alongside ghost hostels, used as a proxy for long-term housing loss. For buildings that contain multiple FREH listings, see ghost hotel. For clusters of private rooms, see ghost hostel.

Ghost hostel: A cluster of private-room STR listings which may appear to be multiple spare bedrooms but are in fact an entire housing unit that has been subdivided into multiple dedicated STRs. We identify ghost hostels using a spatial analysis technique available at https://github.com/UPGo-McGill/ghost. Alongside FREH listings, used as a proxy for long-term housing loss.

Ghost hotel: Multiple frequently rented entire-home (FREH) listings located in a single building.

Listing type: One of “entire home or apartment”, “private room”, “shared room”, or “hotel room”, which an STR host chooses on Airbnb or VRBO to characterize their listing. Entire-home listings are the most common listing type in Vancouver, and they include any STR unit that is available entirely to the guests, which could be a single-family home, a townhouse, a condominium unit, or a secondary suite.

LTR (long-term rental): In this report, a long-term rental is a housing unit available for rent for extended periods of time (generally a year), in contrast to a short-term rental. It can include monthly or yearly rental arrangements. In this report, data from the online classified ad sites Kijiji and Craigslist were used to analyze the LTR market.  

Multilisting: A listing operated by a host who is simultaneously operating other listings in such a manner that the listings cannot all be located at the host’s principal residence. If one host has two or more entire-home listings or three or more private-room listings active on the same day, those are multilistings.

STR - short-term rental: A housing unit available for rent for 31 days or fewer, typical of vacation rental platforms. In this report, we use STR to refer to a rental advertised on Airbnb or VRBO.  

Vacancy rate: The CMHC calculates vacancy rates based on rental apartment structures and rental row (townhouse) structures. Owner-occupied units are not included in the rental building unit count. See CMHC (nd) for specifics.

\newpage